name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'The number of the pull request to review'
        required: true

permissions:
  pull-requests: write
  actions: read
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine PR Number
        id: pr_number
        run: |
          if [ -n "${{ github.event.inputs.pull_request_number }}" ]; then
            echo "pr_number=${{ github.event.inputs.pull_request_number }}" >> $GITHUB_OUTPUT
          else
            echo "pr_number=${{ github.event.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Run Review Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          npm install -g @google/gemini-cli
          ./scripts/code-review.sh ${{ steps.pr_number.outputs.pr_number }}

      - name: Upload Review Artifact
        uses: actions/upload-artifact@v4
        with:
          name: review
          path: review.md

      - name: Post Review Comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          if ! grep -q "This looks great! No suggestions." review.md; then
            gh pr comment ${{ steps.pr_number.outputs.pr_number }} --body-file review.md
          fi
